name: Build & test

on:
  push:
    branches: [ main, develop ]
    paths:
    - 'MatroskaLib/**'
    - 'MkvDefaultTrackChanger/**'
    - 'TestMkvFiles/**'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
