name: Build & test

on:
  push:
    branches: [ main, develop ]
    paths:
    - 'MatroskaLib/**'
    - 'MkvDefaultTrackChanger/**'
    - 'TestMkvFiles/**'
    - '.github/workflows/build-and-test.yml'
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: FedericoCarboni/setup-ffmpeg@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
